name: simple pipeline

on:
  push:
    branches:
      - master

jobs:
  job-build:
    name: Build
    runs-on: ubuntu-late

  steps:
    - name: Upload html
      uses: actions/upload-artifact@v4
      with:
        name: html
        path: index.html
  
    - name: Deploy Artifact       
        run: netlify deploy --prod \
            --dir=out \
            --site ${{ secret.NETLIFY_SITE_ID }} \
            --auth ${{ secret.NETLIFY_API_TOKEN }}
 