name: project1

env:
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  NETLIFY_API_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  job-build:
    name: Build
    runs-on: ubuntu-late
    steps:
      - name: Upload html
        uses: actions/upload-artifact@v4
        with:
          name: html
          path: project1/index.html   
      - name: Deploy Artifact       
        run: |
          netlify deploy --prod \
            --dir=out \
            --site $NETLIFY_SITE_ID \
            --auth $NETLIFY_API_TOKEN
 